<?php
$occupation=[
"Labor contractor",
"Animal scientist",
"Medical records technician",
"Personnel services specialist",
"Real estate rental agent",
"Plating and coating machine tender",
"Food processing occupation",
"Hydrographic surveyor",
"Wastewater treatment system operator",
"Benefits administrator",
"Foreign language translator",
"Pediatric dentist",
"Gaming services",
"Mathematical technician",
"Bleaching and dyeing machine operator",
"Land agent",
"Aircraft and avionics service technician",
"Tax accountant",
"Loading machine operator",
"Checker",
"Refuge manager",
"Colorist",
"Administrative assistant for human resource",
"Residence leasing agent",
"Maid",
"Admissions officer",
"Billing and posting machine operator",
"Precious stone and metal worker",
"Curator",
"New accounts clerk",
"Conservator",
"Order filler",
"Phlebotomist",
"Guitar repairer",
"Computer clerk",
"Tax collector",
"Facilitator",
"Administrative project coordinator",
"Commentator",
"Diesel service mechanic",
"Pharmacy technician",
"Addictions nurse",
"Nurse practitioner",
"Log grader",
"Resort desk clerk",
"Maxillofacial surgeon",
"Tour bus driver",
"Clergy"
];
